baseURL: http://www.dataengconf.com.au/
languageCode: en-us
title: DataEngConf - Sydney
theme: leo-fresh
googleAnalytics: #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/fresh.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: DataEngConf Sydney
    # Hero subtitle (optional)
    subtitle: Tuesday, 4th of August 2020 (Main conference). Workshops on the 3rd!
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    url: /#about
  - title: Sponsors
    url: /#sponsors
  - title: Speakers
    url: /#speakers
  - title: Location
    url: /#location
  - title: Code of Conduct
    url: /#codeconduct
  - title: Organisers
    url: /#organisers

  
  about:
    title: About
    # subtitle: Thank you!

    # subtitle: Thank you! 
    # first_column:
    # - title: Learn
    #   # Icon (from /images/illustrations/icons/___.svg)
    #   icon: sydney_city.jpg
    # - title: Create
    #   icon: Collaborate
    # - title: Collaborate
    #   icon: collaborate_computer_2.jpg


  sponsors:
    title: Sponsors
    # subtitle: Thank you!

  speakers:
    title: Speakers
    # subtitle: And we know it
    # first_column:
    # - title: Powerful and unified interface
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   # Icon (from /images/illustrations/icons/___.svg)
    #   icon: laptop-globe
    # second_column:
    # - title: Cross-device synchronisation
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   icon: doc-sync
    # third_column:
    # - title: Nomad system
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   icon: mobile-feed
  
  location:
    title: Location
    # subtitle: Thank you!
  
  codeconduct:
    title: Code Of Conduct
    # subtitle: Thank you!

  # TODO: Potentially make tiles smaller
  organisers:
    title: Organisers
    subtitle: Great power comes with great responsibility
    first_column:
    - title: Peter Hanssens
      icon: mouse-globe
      # text: This is some explanatory text that is on two rows
    - title: Leo Hoare
      icon: laptop-cloud
      # text: This is some explanatory text that is on two rows
    second_column:
    - title: Karen Davis
      icon: mouse-globe
      # text: This is some explanatory text that is on two rows
    - title: Yash Sharma
      icon: laptop-cloud
      # text: This is some explanatory text that is on two rows
    - title: Wade Jensen
      icon: plug-cloud
      # text: This is some explanatory text that is on two rows
    third_column:
    - title: Simon Aubury
      icon: mouse-globe
      # text: This is some explanatory text that is on two rows
    - title: David Tout
      icon: laptop-cloud
      # text: This is some explanatory text that is on two rows




  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://twitter.com/lucperkins
        icon: twitter
      - link: https://linkedin.com/dataengconfau
        # Icons are from Font Awesome
        icon: linkedin
    # bulmalogo: true
    quicklinks:
      column1:
        title: "Sponsors"
        links:
        - text: Sponsorship Prospectus
          link: /
        # - text: Why choose our product?
        #   link: /
        # - text: Compare features
        #   link: /
        # - text: Our roadmap
        #   link: /
        # - text: AGB
        #   link: /agb
      column2:
        title: "Venue"
        links:
        - text: Coming Soon!
          link: /
        # - text: User guides
        #   link: /
        # - text: Admin guide
        #   link: /
        # - text: Developers
        #   link: /
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
